import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import api from '../../services/api';
import ImageLightbox from '../common/ImageLightbox';

export default function ImageHistory({ isOpen, onClose }) {
    const [images, setImages] = useState([]);
    const [loading, setLoading] = useState(false);
    const [selectedLightboxImage, setSelectedLightboxImage] = useState(null);

    useEffect(() => {
        if (isOpen) {
            fetchImages();
        }
    }, [isOpen]);

    const fetchImages = async () => {
        setLoading(true);
        try {
            const response = await api.get('/files');
            // Filter for images generated by VisualAgent (stored in storage/images)
            const filtered = response.data.filter(file =>
                file.mime_type?.startsWith('image/') &&
                (file.file_path?.includes('storage/images') || file.stored_filename?.startsWith('gen_'))
            ).sort((a, b) => new Date(b.uploaded_at) - new Date(a.uploaded_at));

            setImages(filtered);
        } catch (error) {
            console.error('Failed to fetch image history:', error);
        } finally {
            setLoading(false);
        }
    };

    const handleDownload = (img) => {
        const baseUrl = import.meta.env.VITE_API_BASE_URL || 'http://127.0.0.1:8000';
        const url = `/storage/images/${img.stored_filename}`;
        const fullUrl = `${baseUrl}${url}`;

        const link = document.createElement('a');
        link.href = fullUrl;
        link.download = img.filename;
        link.target = '_blank';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    };

    return (
        <AnimatePresence>
            {isOpen && (
                <>
                    {/* Backdrop */}
                    <motion.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        onClick={onClose}
                        className="fixed inset-0 bg-black/60 backdrop-blur-sm z-[110]"
                    />

                    {/* Sidebar */}
                    <motion.div
                        initial={{ x: '100%' }}
                        animate={{ x: 0 }}
                        exit={{ x: '100%' }}
                        transition={{ type: 'spring', damping: 25, stiffness: 200 }}
                        className="fixed right-0 top-0 bottom-0 w-full max-w-md bg-dark-900 border-l border-dark-700 z-[120] shadow-2xl flex flex-col"
                    >
                        {/* Header */}
                        <div className="p-6 border-b border-dark-700 flex items-center justify-between bg-dark-800/50">
                            <div>
                                <h2 className="text-xl font-bold text-white">🖼️ Image Gallery</h2>
                                <p className="text-xs text-dark-400 mt-1">Your AI creations history</p>
                            </div>
                            <button
                                onClick={onClose}
                                className="w-10 h-10 flex items-center justify-center rounded-xl bg-dark-700 text-dark-400 hover:text-white hover:bg-dark-600 transition-all"
                            >
                                ✕
                            </button>
                        </div>

                        {/* Content */}
                        <div className="flex-1 overflow-y-auto p-6 scrollbar-hide no-scrollbar">
                            {loading ? (
                                <div className="flex flex-col items-center justify-center h-64 gap-4">
                                    <div className="animate-spin w-8 h-8 border-2 border-primary-500 border-t-transparent rounded-full" />
                                    <p className="text-dark-400 text-sm">Loading history...</p>
                                </div>
                            ) : images.length === 0 ? (
                                <div className="text-center py-20">
                                    <div className="text-5xl mb-4 opacity-20">🎨</div>
                                    <p className="text-dark-400">No images generated yet.</p>
                                    <p className="text-xs text-dark-500 mt-2">Start a chat with Visual Agent!</p>
                                </div>
                            ) : (
                                <div className="grid grid-cols-2 gap-4">
                                    {images.map((img) => (
                                        <motion.div
                                            key={img.id}
                                            initial={{ opacity: 0, scale: 0.9 }}
                                            animate={{ opacity: 1, scale: 1 }}
                                            onClick={() => setSelectedLightboxImage(`${import.meta.env.VITE_API_BASE_URL || 'http://127.0.0.1:8000'}/storage/images/${img.stored_filename}`)}
                                            className="group relative aspect-square rounded-2xl overflow-hidden border border-dark-700 bg-dark-800 cursor-zoom-in"
                                        >
                                            <img
                                                src={`${import.meta.env.VITE_API_BASE_URL || 'http://127.0.0.1:8000'}/storage/images/${img.stored_filename}`}
                                                alt={img.filename}
                                                className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110"
                                            />

                                            {/* Hover Overlay */}
                                            <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/40 to-transparent opacity-0 group-hover:opacity-100 transition-opacity flex flex-col justify-end p-3">
                                                <p className="text-[10px] text-white/70 line-clamp-2 mb-2 italic">
                                                    {img.filename.replace('SDXL: ', '').replace('...', '')}
                                                </p>
                                                <div className="flex gap-2">
                                                    <button
                                                        onClick={() => handleDownload(img)}
                                                        className="flex-1 py-1.5 bg-primary-500 hover:bg-primary-400 text-white rounded-lg text-[10px] font-bold transition-colors"
                                                    >
                                                        Download
                                                    </button>
                                                </div>
                                            </div>
                                        </motion.div>
                                    ))}
                                </div>
                            )}
                        </div>

                        {/* Footer */}
                        <div className="p-6 border-t border-dark-700 text-center">
                            <button
                                onClick={fetchImages}
                                className="text-xs text-primary-400 hover:text-primary-300 transition-colors"
                            >
                                🔄 Refresh Gallery
                            </button>
                        </div>
                    </motion.div>
                </>
            )}

            <ImageLightbox
                isOpen={!!selectedLightboxImage}
                imageUrl={selectedLightboxImage}
                onClose={() => setSelectedLightboxImage(null)}
            />
        </AnimatePresence>
    );
}
