import React from 'react';
import FileManagerComponent from '../components/files/FileManager';

const FileManager = () => {
    return (
        <div className="min-h-screen bg-dark-900 pt-20 px-4 pb-12">
            <div className="max-w-7xl mx-auto">
                <div className="mb-8">
                    <h1 className="text-3xl font-bold text-white mb-2">File Manager</h1>
                    <p className="text-dark-400">Manage and access all files generated by your AI agents.</p>
                </div>

                <div className="bg-dark-800 rounded-2xl border border-dark-700 overflow-hidden">
                    <FileManagerComponent />
                </div>
            </div>
        </div>
    );
};

export default FileManager;
