"""Nexus AI - Task Models.

This module defines the Task and Subtask models, which track the execution 
of user requests and their decomposition into specialized agent actions.
"""

from sqlalchemy import Column, Integer, String, Text, Float, DateTime, ForeignKey, Enum, JSON, Index
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from database import Base
import enum


class TaskStatus(str, enum.Enum):
    """Enum for task status"""
    QUEUED = "queued"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"


class Task(Base):
    """Represents a high-level user request or automated job.
    
    The Task model tracks the lifecycle of a user prompt, from queuing through 
    strategic analysis to final output generation. It links to a Project 
    if it's part of a larger multi-phase workflow.
    
    Attributes:
        id: Primary key identifier.
        user_id: Foreign key to the owner.
        project_id: Optional foreign key to a managing project.
        user_prompt: The original request text.
        status: Current state (queued, in_progress, completed, failed).
        output: The final synthesized result.
    """
    
    __tablename__ = "tasks"
    
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    project_id = Column(Integer, ForeignKey("projects.id", ondelete="SET NULL"), nullable=True, index=True)
    user_prompt = Column(Text, nullable=False)
    status = Column(String(20), default=TaskStatus.QUEUED.value, index=True)
    complexity_score = Column(Float, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    completed_at = Column(DateTime(timezone=True), nullable=True)
    output = Column(Text, nullable=True)
    
    # Feedback columns (Phase 5)
    user_rating = Column(Integer, nullable=True)  # 1-5 rating
    user_feedback = Column(Text, nullable=True)  # Text feedback
    feedback_timestamp = Column(DateTime(timezone=True), nullable=True)
    
    # Relationships
    user = relationship("User", back_populates="tasks")
    project = relationship("Project", back_populates="tasks")
    subtasks = relationship("Subtask", back_populates="task", cascade="all, delete-orphan")
    agent_messages = relationship("AgentMessage", back_populates="task", cascade="all, delete-orphan")
    files = relationship("File", back_populates="task")
    
    # Composite indexes for common query patterns
    __table_args__ = (
        Index("ix_tasks_user_id_status", "user_id", "status"),
        Index("ix_tasks_user_id_created_at", "user_id", "created_at"),
    )
    
    def __repr__(self):
        return f"<Task(id={self.id}, status='{self.status}', user_id={self.user_id})>"


class Subtask(Base):
    """Represents a granular action performed by a specific AI agent.
    
    Subtasks are generated by the Orchestrator or ManagerAgent as parts 
    of a larger Task. Each subtask is assigned to a specialized agent 
    (e.g., ResearchAgent, CodeAgent).
    
    Attributes:
        id: Primary key identifier.
        task_id: Foreign key to the parent Task.
        assigned_agent: The name of the agent executing this subtask.
        input_data: JSON payload containing parameters for the agent.
        status: Execution state of this specific subtask.
    """
    
    __tablename__ = "subtasks"
    
    id = Column(Integer, primary_key=True, index=True)
    task_id = Column(Integer, ForeignKey("tasks.id", ondelete="CASCADE"), nullable=False, index=True)
    assigned_agent = Column(String(100), nullable=False, index=True)
    input_data = Column(JSON, nullable=True)
    output_data = Column(JSON, nullable=True)
    status = Column(String(20), default=TaskStatus.QUEUED.value, index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    completed_at = Column(DateTime(timezone=True), nullable=True)
    error_message = Column(Text, nullable=True)
    
    # Relationships
    task = relationship("Task", back_populates="subtasks")
    
    def __repr__(self):
        return f"<Subtask(id={self.id}, agent='{self.assigned_agent}', status='{self.status}')>"
